config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'homes#top'

  resources :users, only: [:show, :edit, :update, :index, :destroy]

  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :post_comments, only: [:create, :destroy]
  end

  get "users/:id" => "users#show", as: 'show_user'

  get "home/about" => 'homes#about'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
  	protected
  	def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    	devise_parameter_sanitizer.permit(:log_in, keys: [:name])
  	end

	def after_sign_in_path_for(resource)
		show_user_path(resource)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@book.user = current_user
		if @book.save
			flash[:notice] = "Book was successfully updated!"
			redirect_to book_path(@book.id)
		else
			flash[:notice] = "error!"
			redirect_to books_path
		end
	end

	def index
		@books = Book.all
		@user = current_user
	end

	def show
		@book = Book.find(params[:id])
		@user = @book.user
		@post_comment = PostComment.new
		@book.post_comments = @book.post_comments.all
	end

	def edit
		@book = Book.find(params[:id])
		@user = @book.user
		if current_user == @user
			flash[:notice] = "Profile was successfully updated!"
			@book = Book.find(params[:id])
		else
			flash[:notice] = "error!"
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "Book was successfully updated!"
			redirect_to book_path(@book.id)
		else
			flash[:notice] = "error!"
			render :edit
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params[:book].permit(:title, :body, :user_id)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		#上のと下のは同義？？
		#favorite = Favorite.new(book_id: book.id)
		#favorite.user_id = current_user.id
		favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		#下のコードだと他のユーザーのfavoも消せちゃう
		#favorite = Favorite.find_by(book_id: book.id)
		#favorite.user_id = current_user.id
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
	end

	def about
	end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
		book = Book.find(params[:book_id])
		comment = PostComment.new(post_comment_params)
		comment.user_id = current_user.id
		comment.book_id = book.id
		comment.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		book = Book.find(params[:book_id])
		comment = PostComment.find_by(params[:id])
		comment.user_id = current_user.id
		comment.book_id = book.id
		comment.destroy
		redirect_back(fallback_location: root_path)
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

	def show
		@user = User.find(params[:id])
		@book = @user.books
	end

	def edit
		@user = User.find(params[:id])
		if current_user == @user
			flash[:notice] = "Profile was successfully updated!"
			@user = User.find(params[:id])
		else
			flash[:notice] = "error!"
			redirect_to user_path(current_user.id)
		end
	end

	def update
		user = User.find(params[:id])
		if user.update(user_params)
			flash[:notice] = "Profile was successfully updated!"
			redirect_to user_path(user.id)
		else
			flash[:notice] = "error!"
			redirect_to user_path(user.id)
		end
	end

	def index
		@users = User.all
		@user = current_user
	end

	def destroy
		flash[:notice] = "Signed out successfully,"
		redirect_to root_path
	end

	private
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_favo_comment.html.erb
<!--いいね機能-->
                  <th>
                    <% if book.favorited_by?(current_user) %>
                      <li>
                        <%= link_to book_favorites_path(book.id), method: :delete do %>
                          <i class="fa fa-heart", aria-hidden="true" style="color: red;"></i>
                          <%= book.favorites.count %>
                        <% end %>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to book_favorites_path(book.id), method: :post do %>
                          <i class="fa fa-heart-o", aria-hidden="true"></i>
                          <%= book.favorites.count %>
                        <% end %>
                      </li>
                    <% end %>
                  </th>
                  <th>コメント数：<%= book.post_comments.count %></th>
                  <!--いいね機能最後尾-->

app/views/books/_newbookform.html.erb
            <%= form_with model: current_user.books, url: books_path, local: true do |form| %>

              <div class="row">
                <%= form.label :title %>
                <%= form.text_field :title, class: "col-xs-12" %>
              </div>
              <div class="row">
                <%= form.label :body %>
                <%= form.text_area :body, class: "col-xs-12" %>
              </div>
              <div class="row">
                <%= form.submit "Create Book", class:"btn btn-primary col-xs-12" %>
              </div>
            <% end %>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">

		<% if flash[:notice] %>
    		<div class="flash">
    			<%= flash[:notice] %>
    		</div>
		<% end %>

		<div class="col-md-6 col-md-offset-3">

			<%= form_with model: @book, url: book_path, local: true do |form| %>

				<h2>Editing Book</h2>
				<div class="field_row">
					<p>Title</p>
					<%= form.text_field :title %>
				</div>
				<div class="field_row">
					<p>Opinion</p>
					<%= form.text_area :body %>
				</div>
				<div class="action_row">
					<%= form.submit 'Update Book',  class: "btn btn-primary col-xs-12" %>
				</div>
			<% end %>

			<div class="row">
				<%= link_to 'Show', book_path(@book.id) %>
				<%= link_to 'Back', books_path %>
			</div>

	</div>

</div>

app/views/books/index.html.erb
<body>

  <div class="body">
    <div class="container">

      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <div class="row col-xs-offset-1">

        <div class="col-xs-3">
          <!--user_profileここから-->
          <h2>User info</h2>
            <table class="table">
              <thead>
                <tr>
                  <th>
                    <%= attachment_image_tag @user, :profile_image, :fill,70, 70, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                  </th>
                  <th colspan></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>Name</th>
                  <th><%= @user.name %></th>
                </tr>
                <tr>
                  <th>Introduction</th>
                  <th><%= @user.introduction %></th>
                </tr>
              </tbody>
            </table>
            <div class="row">
                <%= link_to sanitize('<i class="glyphicon glyphicon-wrench"></i>'), edit_user_path(current_user.id), class: "btn btn-default col-xs-10 col-xs-offset-1" %>
            </div>
          <!--User_profileここまで-->
          <!--投稿フォームここから-->
          <h2>New books</h2>
          <%= render 'books/newbookform' %>
            <!--投稿フォームここまで-->
        </div>

        <div class="table-responsive col-xs-9">
          <h2>Books</h2>
          <table class="table">
            <thead>
              <tr>
                <th colspan="1"></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="2"></th>
              </tr>
            </thead>

            <% @books.each do |book| %>
              <tbody>
                <tr>
                  <th>
                    <%= link_to user_path(book.user.id) do %>
                      <%= attachment_image_tag book.user,:profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg"  %>
                    <% end %>
                  </th>
                  <th>
                    <%= link_to book_path(book.id) do %>
                      <%= book.title %>
                    <% end %>
                  </th>
                  <th><%= book.body %></th>

                 <!--いいね機能-->
                  <th>
                    <% if book.favorited_by?(current_user) %>
                      <li>
                        <%= link_to book_favorites_path(book.id), method: :delete do %>
                          <i class="fa fa-heart", aria-hidden="true" style="color: red;"></i>
                          <%= book.favorites.count %>
                        <% end %>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to book_favorites_path(book.id), method: :post do %>
                          <i class="fa fa-heart-o", aria-hidden="true"></i>
                          <%= book.favorites.count %>
                        <% end %>
                      </li>
                    <% end %>
                  </th>
                  <th>コメント数：<%= book.post_comments.count %></th>
                  <!--いいね機能最後尾-->
                </tr>
              </tbody>
            <% end %>

          </table>
        </div>

      </div>

    </div>
  </div>

</body>

app/views/books/show.html.erb
<body>

  <div class="body">
  	<div class="container">
  		<% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>

  		<div class="row col-xs-offset-1">

          <div class="col-xs-3">
          <!--user_profileここから-->
          <h2>User info</h2>
            <table class="table">
              <thead>
                <tr>
                  <th>
                    <%= attachment_image_tag @book.user, :profile_image, :fill, 70, 70, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                  </th>
                  <th colspan></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>Name</th>
                  <th><%= @book.user.name %></th>
                </tr>
                <tr>
                  <th>Introduction</th>
                  <th><%= @book.user.introduction %></th>
                </tr>
              </tbody>
            </table>
            <div class="row">
                <%= link_to sanitize('<i class="glyphicon glyphicon-wrench"></i>'), edit_user_path(current_user.id), class: "btn btn-default col-xs-10 col-xs-offset-1s" %>
            </div>
          <!--User_profileここまで-->
          <!--投稿フォームここから-->
          <h2>New books</h2>
          <%= render 'books/newbookform' %>
            <!--投稿フォームここまで-->
        </div>

  			<div class="table-hover col-xs-9">
  				<h2>Book detail</h2>
          <table class="table">
            <tr>
              <th>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg' %>
                <br>
                <%= link_to user_path(@book.user.id) do %>
                  <%= @book.user.name %>
                <% end %>
              </th>
              <th>
                <%= link_to book_path(@book.id) do %>
                  <%= @book.title %>
                <% end %>
              </th>
              <th><%= @book.body %></th>

              <% if current_user.id == @book.user_id %>

                <th><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success" %></th>
                <th><%= link_to "Destroy", book_path(@book.id), method: :delete, class:"btn btn-danger", "data-confirm" => "Are you sure?" %></th>

              <% end %>

              <!--いいね/コメント機能-->
                  <th>
                    <% if @book.favorited_by?(current_user) %>
                      <li>
                        <%= link_to book_favorites_path(@book.id), method: :delete do %>
                          <i class="fa fa-heart", aria-hidden="true" style="color: red;"></i>
                          <%= @book.favorites.count %>
                        <% end %>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to book_favorites_path(@book.id), method: :post do %>
                          <i class="fa fa-heart-o", aria-hidden="true"></i>
                          <%= @book.favorites.count %>
                        <% end %>
                      </li>
                    <% end %>
                  </th>
                  <th>コメント数：<%= @book.post_comments.count %></th>
                  <!--いいね機能最後尾-->

            </tr>
          </table>

          <!--コメント機能-->
          <div class="row, comment_index">
            <table class="table">
              <h3>コメント一覧</h3>
              <% @book.post_comments.each do |post_comment| %>
                <tr>
                  <th>
                  <%= attachment_image_tag post_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                  </th>
                  <th><%= post_comment.comment %></th>
                  <% if post_comment.user == current_user %>
                    <th>
                      <%= link_to "destroy", book_post_comments_path(post_comment.book, post_comment), method: :delete, class: "btn btn-danger" %>
                    </th>
                  <% end %>
                </tr>
              <% end %>
            </table>
          </div>

          <div class="row, col-xs-12">
              <%= form_for [@book, @post_comment] do |f| %>
                <%= f.text_area :comment %>
                <%= f.submit "送信", method: :post  %>
              <% end %>
          </div>
          <!--コメント機能ここまで-->
  			</div>
  		</div>
	</div>
  </div>
</body>

app/views/homes/_header.html.erb
<!--headerここから-->
	<nav class="nav navbar-default navbar-inverse">
		<!--↑navbar-inverse追加でヘッダー色反転-->
		<div class="container">
  			<div class="navbar-header">

  				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample4">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Bookers</a>
			</div>

  			<div class="collapse navbar-collapse" id="navbarEexample4">
  				<ul class="nav navbar-nav navbar-right">
					<li><a href="/">
						<span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></a>
					</li>
  					<li><a href="/home/about">
  						<span class="glyphicon glyphicon-link" aria-hidden="true"> About</span></a>
  					</li>
  					<li><a href="/users/sign_up">
  						<span class="glyphicon glyphicon-edit" aria-hidden="true"> sign up</span></a>
  					</li>
  					<li><a href="/users/sign_in">
  						<span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span></a>
  					</li>
  				</ul>
  			</div>
  		</div>
  	</nav>
  	<!--headerここまで-->

app/views/homes/about.html.erb

<body>
    <div class="body">
      <div class="container">
        <!--ここにサクセスメッセージ-->
        <div class="row">
          <div class="col-md-6 col-md-offset-1">
          <!--class="top-message"-->
          <h1>welcome to
            <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong></span>
            !!
          </h1>
        </div>
      </div>
    </div>
</body>

app/views/homes/top.html.erb
<% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
<% end %>

<body>
  	<div class="body">
  		<div class="container">
  			<!--ここにサクセスメッセージ-->
  			<div class="row">
  				<div class="col-md-6 col-md-offset-3">
  				<!--class="top-message"-->
					<h1>welcome to
						<span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong></span>
						!!
					</h1>
					<P>In <span class="glyphicon glyphicon-book" aria-hidden="true"><strong>Bookers</strong></span>,</P>
					<P>you can share and exchange your opinions,inpressions,and emotions</P>
					<p>about various books!</p>
				</div>
			</div>
			<div class="container">
				<div class="btn-group-vertical col-md-5 col-md-offset-3" role="group">
					<a href="/users/sign_in" class="btn btn-info">Log in</a>
					<a href="/users/sign_up" class="btn btn-success">Sign up</a>
				</div>
			</div>
		</div>
</body>

app/views/layouts/_error_messages.html.erb


<% if @book.errors.any? %>
	<div id="error_explanation" class="alert alert-danger">
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
  	<!--headerここから-->
  	<div id="slidemenu">
  		<nav class="nav navbar-default navbar-inverse text-white">
  			<div class="container">
  			<div class="navbar-header">

  				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample4">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>

			</div>

			<div class="container navbar-collapse" id="navbarEexample4">

        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-left text-muted">
            <h4>Bookers</h4>
          </ul>
          <nav>
  				<ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to sanitize('<i class="glyphicon glyphicon-home"></i> Home'),user_path(current_user.id) %>
              </li>
              <li>
                <%= link_to sanitize('<i class="glyphicon glyphicon-user"></i> Users'),users_path %>
              </li>
              <li>
                <%= link_to sanitize('<i class="glyphicon glyphicon-book"></i> Books'),books_path %>
              </li>
              <li>
                <%= link_to sanitize('<i class="glyphicon glyphicon-user"></i> logout'),destroy_user_session_path, method: :delete %>
              </li>
          </ul>
          </nav>
  			<% else %>

          <ul class="nav navbar-nav navbar-right">

						<li><a href="/">
              <span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span></a>
            </li>
              <li><a href="/home/about">
                <span class="glyphicon glyphicon-link" aria-hidden="true"> About</span></a>
              </li>
              <li><a href="/users/sign_up">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"> sign up</span></a>
              </li>
              <li><a href="/users/sign_in">
                <span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span></a>
              </li>
          </ul>

 				<% end %>

  			</div>
  			</div>
  		</nav>
  	</div>
  	<!--headerここまで-->

    <!--サクセスメッセージ-->
    <!--サクセスメッセージ-->

    <%= yield %>

    <!--フッターここから-->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-offset-9 navbar-right">
					<p>CopyRight Infratop.inc<p>
				</div>
			</div>
		</div>
	</footer>
	<!--フッターここまで-->

  </body>
</html>

app/views/users/edit.html.erb
<div class="container">

	<div class="row col-xs-offset-1">

		<h2>User info</h2>
		<%= form_for(@user) do |f| %>
		<p>Name</p>
			<%= f.text_field :name %>
			<P>Image</P>
			<%= f.attachment_field :profile_image %>
			<p>Introduction</p>
			<%= f.text_area :introduction %>
			<%= f.submit 'Update User' %>
		<% end %>

	</div>
</div>

app/views/users/index.html.erb
<body>

  <div class="body">
    <div class="container">

      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <div class="row col-xs-offset-1">

        <div class="col-xs-3">
          <!--user_profileここから-->
          <h2>User info</h2>
            <table class="table">
              <thead>
                <tr>
                  <th>
                    <%= attachment_image_tag @user, :profile_image, :fill,70, 70, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                  </th>
                  <th colspan></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>Name</th>
                  <th><%= @user.name %></th>
                </tr>
                <tr>
                  <th>Introduction</th>
                  <th><%= @user.introduction %></th>
                </tr>
              </tbody>
            </table>
            <div class="row">
                <%= link_to sanitize('<i class="glyphicon glyphicon-wrench"></i>'), edit_user_path(current_user.id), class: "btn btn-default col-xs-10 col-xs-offset-1" %>
            </div>
          <!--User_profileここまで-->
          <!--投稿フォームここから-->
          <div class="filed row">
            <h2>New books</h2>

            <%= form_with model: @user.books, url: books_path, local: true do |form| %>


              <h4>Title</h4>
              <%= form.text_field :title, class:"col-xs-12 mb-5" %>
              <h4>Opinion</h4>
              <%= form.text_area :body, class:"col-xs-12 m-10" %>
              <%= form.submit "Create Book", class:"btn btn-primary col-xs-12 my-5" %>
            <% end %>
            <!--投稿フォームここまで-->
          </div>
        </div>

        <div class="table-responsive col-xs-9">
          <h2>Books</h2>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="1"></th>
              </tr>
            </thead>
            <% @users.each do |user| %>
              <tbody>
                <tr>
                  <th>
                      <%= attachment_image_tag user,:profile_image, :fill, 30, 30, format: 'jpg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg"  %>
                  </th>
                  <th>
                      <%= user.name %>
                  </th>
                  <th>
                    <%= link_to "Show", user_path(user.id) %>
                  </th>
                </tr>
              </tbody>
            <% end %>

          </table>
        </div>

      </div>

    </div>
  </div>

</body>

app/views/users/show.html.erb
<body>

  <div class="body">
  	<div class="container">

      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>

  		<div class="row col-xs-offset-1">

        <div class="col-xs-3">
          <!--user_profileここから-->
          <h2>User info</h2>
            <table class="table">
              <thead>
                <tr>
                  <th>
                    <%= attachment_image_tag @user, :profile_image, :fill,70, 70, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                  </th>
                  <th colspan></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>Name</th>
                  <th><%= @user.name %></th>
                </tr>
                <tr>
                  <th>Introduction</th>
                  <th><%= @user.introduction %></th>
                </tr>
              </tbody>
            </table>
            <div class="row">
                <%= link_to sanitize('<i class="glyphicon glyphicon-wrench"></i>'), edit_user_path(@user), class: "btn btn-default col-xs-10 col-xs-offset-1" %>
            </div>
          <!--User_profileここまで-->
          <!--投稿フォームここから-->

          <div class="filed row">
            <h2>New books</h2>

            <%= form_with model: @user.books, url: books_path, local: true do |form| %>


              <h4>Title</h4>
              <%= form.text_field :title, class:"col-xs-12 mb-5" %>
              <h4>Opinion</h4>
              <%= form.text_area :body, class:"col-xs-12 m-10" %>
              <%= form.submit "Create Book", class:"btn btn-primary col-xs-12 my-5" %>
            <% end %>
            <!--投稿フォームここまで-->
          </div>
        </div>

  			<div class="col-xs-9">
  		    <h2>Books</h2>
          <table class="table table-hover">
            <thead>
              <tr>
                <th colspan="1"></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>
            <% @book.each do |book| %>
              <tbody>
                <tr>
                  <th>
                    <%= link_to user_path(book.user.id) do %>
                      <%= attachment_image_tag book.user,:profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg"  %>
                    <% end %>
                  </th>
                  <th>
                    <%= link_to book_path(book.id) do %>
                      <%= book.title %>
                    <% end %>
                  </th>
                  <th><%= book.body %></th>
            <!--いいね機能-->
                  <th>
                    <% if book.favorited_by?(current_user) %>
                      <li>
                        <%= link_to book_favorites_path(book.id), method: :delete do %>
                          <i class="fa fa-heart", aria-hidden="true" style="color: red;"></i>
                          <%= book.favorites.count %>
                        <% end %>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to book_favorites_path(book.id), method: :post do %>
                          <i class="fa fa-heart-o", aria-hidden="true"></i>
                          <%= book.favorites.count %>
                        <% end %>
                      </li>
                    <% end %>
                  </th>
                  <th>コメント数：<%= book.post_comments.count %></th>
                  <!--いいね機能最後尾-->
                </tr>
              </tbody>
            <% end %>
          </table>
  			</div>

  		</div>

    </div>
  </div>

</body>